cc_test(
  name = "arena_test",
  srcs = ["arena_test.cc"],
  size = "small",
  deps = [
    "@gtest//:gtest_main",
    "//runtime:bullet",
  ],
)
cc_test(
  name = "persistent_heap_test",
  srcs = ["persistent_heap_test.cc"],
  deps = [
    "@gtest//:gtest_main",
    "//runtime:bullet",
  ],
)
