#!/bin/bash

if [ ! -f "WORKSPACE" ]; then
    echo "fmt must be called from within the workspace. Current directory is $(pwd)"
fi

find runtime/ test/ examples/ -type f -name *.cc -o -name *.h | xargs clang-format -i
